### PR TITLE
Update schema to [uid] for Dgraph v1.1.

### PR DESCRIPTION
**Pull request by danielmai**
https://github.com/dgraph-io/dgraph/issues/3685#issuecomment-512760374 This mutation error appears in Flock when trying to mutate a uid-list edge for Dgraph v1.1 clusters. This PR changes the schema to use the `[uid]` syntax for uid edges. `uid` in Dgraph v1.1 enforces one-to-one associations which, in the case of Flock, isn't the right type for these predicates.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/flock/17)

### CODE REVIEW

**Comment by danielmai** [comment]
Actually, the `author` predicate can be the `uid` type since single every tweet has exactly one author.

**Comment by mangalaman93** [comment]
But then, flock won't work with the older versions. If that's okay, LGTM.

**Comment by danielmai** [comment]
We can check for the Dgraph version from `/health` to decide which schema to set. That should work?

**Comment by danielmai** [comment]
@mangalaman93 now the schema type for the `mention` predicate is `uid` for v1.0 and `[uid]` for v1.1. The version check is based on the response from `/health` — `OK` (v1.0) or a JSON map (v1.1).

**Pull request merged**
